### ISSUE TITLE
Making a compact badge

### ISSUE THREAD

**Issue by djay** [40ants/github-matrix#2]
It would be nice to be able to specify which variables to collapse and not show in the badge.

e.g here I'd rather not show build or python version, just plone-version.
<img width="457" alt="Screen Shot 2021-02-02 at 5 03 54 pm" src="https://user-images.githubusercontent.com/41700/106584835-3fc11a00-6579-11eb-9ea3-7f49f6f50d97.png">

Also the attribution could be much closer and perhaps on top so that if the badge is inline with other badges then they line up. or even better if the attribution was a tooltip (https://talk.commonmark.org/t/abbr-tags-tooltips-using-link-syntax/965)

**Comment by svetlyak40wt** [comment]
Tooltips will not work when badge is inserted into the page via `img`. Tooltips and links will work only if SVG is included as an `iframe`. But this is only possible in the hosted documentation (i.e. gh pages site), not in the README :(

**Comment by svetlyak40wt** [comment]
Please, attach an URL of the GitHub project where did you get this image.

Also, I still don't understand what kind of (compact) picture do you have in mind. A mockup image would help greatly.

**Comment by djay** [comment]
now it seems to have broken even more - https://github.com/collective/collective.pfg.signup.

**Comment by djay** [comment]
@svetlyak40wt here is a mockup of a compact version that would work inline with other badges
<img width="617" alt="Screen Shot 2021-02-09 at 11 48 40 am" src="https://user-images.githubusercontent.com/41700/107317389-26662380-6acd-11eb-8477-e27e8e0b81e1.png">

Ie I just want to ignore certain axis and combine them into a single red or green flag. in this case it would be combining the results of different python versions

**Comment by svetlyak40wt** [comment]
Aha! I have something like that in mind. You'll have an ability to select a part of the workflow by path:

```
matrix.svg?only=main.build.python-version[2.7]
```

**Comment by djay** [comment]
yeah that would solve it. Maybe not as nicely as combining test runs since know that plone 5.2 only works on some versions of python is lost. But hopefully my master is all green :)

Note also the suggestion to put the attribution on top means a inline badge image lines up nicely with others along the bottom

**Comment by svetlyak40wt** [comment]
Hi @djay!

I've added a feature to limit the number of generated badges.

Here its description with examples: https://github-actions.40ants.com/#matrix-subset

Here is example rendering for [collective.pfg.signup](https://github.com/collective/collective.pfg.signup):

```
[![](http://github-actions.40ants.com/collective/collective.pfg.signup/matrix.svg?only=ci.build)](https://github.com/collective/collective.pfg.signup)
```

[![](http://github-actions.40ants.com/collective/collective.pfg.signup/matrix.svg?only=ci.build)](https://github.com/collective/collective.pfg.signup)

**Comment by djay** [comment]
Looks great

**Comment by djay** [comment]
I'm not sure if I'm getting the url format wrong but I still cant seem to ignore part of the matrix to get a more compact badge. For example in the following I just want to she the status of the PLONE_VERSION runs combined

## only=ci.build

[![](https://github-actions.40ants.com/collective/collective.collectionfilter/matrix.svg?only=ci.build)](https://github.com/collective/collective.collectionfilter)

## only=ci.build.PLONE-VERSION
The following doesn't work

[![](https://github-actions.40ants.com/collective/collective.collectionfilter/matrix.svg?only=ci.build.PLONE-VERSION)](https://github.com/collective/collective.collectionfilter)

**Comment by svetlyak40wt** [comment]
This seems like a bug :(
