### ISSUE TITLE
https://github-actions.40ants.com/ is down

### ISSUE THREAD

**Issue by GuillaumeDua** [40ants/github-matrix#8]
# https://github-actions.40ants.com/ is down

## Step to reproduce :

Go to https://github-actions.40ants.com/ in any browser

| browser | error |
|-|-|
| Firefox | `PR_END_OF_FILE_ERROR` |
| Google Chrome | `ERR_CONNECTION_CLOSED` |

## Expected behavior

The good old one 👍

**Comment by svetlyak40wt** [comment]
I know. Heroku deleted my account just because I am Russian.

Have to find time and set up everything on a new hosting :(

сб, 21 мая 2022 г., 19:17 GuillaumeDua ***@***.***>:

**Comment by biphasic** [comment]
Is there something we can do to help?

**Comment by svetlyak40wt** [comment]
No, I'm preparing a custom Kubernetes cluster to host my applications. Will resurrect this service soon ASAP.

**Comment by Aarsh2001** [comment]
Just wanted to know if there were any updates on this, would be of great help, thanks🙂.

> No, I'm preparing a custom Kubernetes cluster to host my applications. Will resurrect this service soon ASAP.

**Comment by svetlyak40wt** [comment]
Guys, finally I've found some time to set up deployment at another hosting. Now service should be alive!

**Comment by svetlyak40wt** [comment]
Thank you for the patience.

**Comment by daroczig** [comment]
https://github-actions.40ants.com seems to be down again
