### ISSUE TITLE
The service works slower than before when it was hosted on Heroku

### ISSUE THREAD

**Issue by Aarsh2001** [40ants/github-matrix#9]
It takes a lot of time to load, and sometimes it just doesn't

**Comment by svetlyak40wt** [comment]
It is not down. Performance problems may be caused by the new servers where I've deployed the application. I need to set up some sort of monitoring on response times to understand what is happening.

**Comment by svetlyak40wt** [comment]
Aarsh2001, could you please provide a link to the GitHub project where you've noticed problems with slow loading?

**Comment by svetlyak40wt** [comment]
Probably loading problems are cause by the caching in the GitHub. It cached all images referenced from the README.

For example, I have a project https://github.com/40ants/ci and GitHub does not render a badge in the Readme. However it is rendered in the project's documentation: https://40ants.com/ci/.

If you experience such problems, try to add some argument to the image address, like:

```
https://github-actions.40ants.com/40ants/ci/matrix.svg?some=123
```

update the README and see if GitHub will update the cache correctly.

**Comment by svetlyak40wt** [comment]
Well, I've found that my service sets `Cache-Control: max-age=900` and GitHub should respect this. Thus problem may be in a longer response time. May be GitHub's cacher just can't wait so long.

**Comment by svetlyak40wt** [comment]
Seems I've found the problem. GitHub token was lost when I've moved to another hosting. Because all requests to GitHub API were unauthorized, there was a very severe rate limit and GitHub Actions sleeper until the limit reset.

Now I've fixed this issue and service should become more responsible.
